---
title: "Chapter 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Library and data
```{r}
library(rethinking)

data(Howell1)
d = Howell1
d2 = d[d$age >= 18,] # data excluding persons under 18 years of age

```

GRID APROX
```{r}
dens(d2$height)

# priors
curve(dnorm(x, 178, 20), from = 100, to = 250) 
curve(dunif(x, 0 , 50), from = -10, to = 60)


sample_mu = rnorm(1e7, 178, 20)
sample_sigma = runif(1e7, 0, 50)
prior_h = rnorm(1e7, sample_mu, sample_sigma)
dens(prior_h)


#posterior
mu.list = seq(from= 140, to = 160, length.out = 200)
sigma.list = seq(from = 4, to = 9, length.out = 200)
post = expand.grid(mu = mu.list, sigma = sigma.list)
post$LL = sapply(1:nrow(post), function(i) sum(dnorm(
  d2$height,
  mean = post$mu[i],
  sd = post$sigma[i],
  log = T
)))
post$prod = post$LL + 
  dnorm(post$mu, 178, 20, T) +
  dunif(post$sigma, 0, 50, T)
post$prob = exp(post$prod - max(post$prod))


contour_xyz(post$mu, post$sigma, post$prob)

image_xyz(post$mu, post$sigma, post$prob)


#sampling
sample.rows = sample(1:nrow(post), size = 1e4, replace = T, prob = post$prob)
sample.mu = post$mu[sample.rows]
sample.sigma = post$sigma[sample.rows]

plot(sample.mu, sample.sigma, cex = 1, pch = 15, col = col.alpha(rangi2, 0.01))

dens(sample.mu)
dens(sample.sigma)

HPDI(sample.mu) #153.8693 - 155.1759 
HPDI(sample.sigma)#7.266332 - 8.195980 
```


QUADRATIC APROXIMATION
```{r}

# MODEL 1----
flist = alist(
  height ~ dnorm(mu, sigma),
  mu ~ dnorm(178, 20),
  sigma ~ dunif(0, 50)
)

m4.1 = map(flist, data=d2)

precis(m4.1)

# MODEL 2----
m4.2 = map(
  alist(
    height ~ dnorm(mu, sigma),
    mu ~ dnorm(178, 0.1),
    sigma ~ dunif(0, 50)
  ), data = d2
)

precis(m4.2)
#-----
vcov(m4.1)
diag(vcov(m4.1))
cov2cor(vcov(m4.1))



#sampling
post = extract.samples(m4.1, n = 1e4)
head(post)
precis(post)

plot(d2$height ~ d2$weight)



# MODEL 3 ----

m4.3 = map(alist(
  height ~ dnorm(mu, sigma),
  mu <- a + b*weight,
  a ~ dnorm(156, 100),
  b ~ dnorm(0, 10),
  sigma ~ dunif(0, 50)
), data = d2)

precis(m4.3, corr = T)

# MODEL 4 ----
d2$weight.c = d2$weight - mean(d2$weight) #Centering weight

m4.4 = map(alist(
  height ~ dnorm(mu, sigma),
  mu <- a + b*weight.c,
  a ~ dnorm(156, 100),
  b ~ dnorm(0, 10),
  sigma ~ dunif(0, 50)
), data = d2)

precis(m4.4, corr = T)



plot( height ~ weight, data = d2)
abline( a = coef(m4.3)["a"], b = coef(m4.3)["b"])

post = extract.samples(m4.3)
post[1:5,]
```

